@Dogshouseservice_HostAddress = http://localhost:5130

GET {{Dogshouseservice_HostAddress}}/ping/
Accept: application/json

###

# GET request to get all dogs
GET {{Dogshouseservice_HostAddress}}/dogs/
Content-Type: application/json

###

# POST request to add Neo
POST {{Dogshouseservice_HostAddress}}/dog/
Content-Type: application/json

{
  "name": "Neo",
  "color": "red & amber",
  "taillength": 22,
  "weight": 32
}

###

# POST request to add Jessy
POST {{Dogshouseservice_HostAddress}}/dog/
Content-Type: application/json

{
  "name": "Jessy",
  "color": "black & white",
  "taillength": 7,
  "weight": 14
}

###
